name: Build Nature Circle APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find and extract project
        run: |
          mkdir -p builder
          unzip -q ./*.zip -d builder

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'



      - name: Find Gradle project
        run: |
          GRADLEW=$(find builder -name gradlew -type f | head -n 1)
          echo "GRADLEW=$GRADLEW" >> $GITHUB_ENV
          echo "PROJECT_DIR=$(dirname "$GRADLEW")" >> $GITHUB_ENV

      - name: Build APK
        run: |
          cd "$PROJECT_DIR"
          chmod +x gradlew
          ./gradlew assembleDebug
          cp app/build/outputs/apk/debug/*.apk "$GITHUB_WORKSPACE/Nature-Circle-debug.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Nature-Circle-APK
          path: Nature-Circle-debug.apk
